package com.parcial2.consul.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HorarioAtencionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHorarioAtencionAllPropertiesEquals(HorarioAtencion expected, HorarioAtencion actual) {
        assertHorarioAtencionAutoGeneratedPropertiesEquals(expected, actual);
        assertHorarioAtencionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHorarioAtencionAllUpdatablePropertiesEquals(HorarioAtencion expected, HorarioAtencion actual) {
        assertHorarioAtencionUpdatableFieldsEquals(expected, actual);
        assertHorarioAtencionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHorarioAtencionAutoGeneratedPropertiesEquals(HorarioAtencion expected, HorarioAtencion actual) {
        assertThat(actual)
            .as("Verify HorarioAtencion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHorarioAtencionUpdatableFieldsEquals(HorarioAtencion expected, HorarioAtencion actual) {
        assertThat(actual)
            .as("Verify HorarioAtencion relevant properties")
            .satisfies(a -> assertThat(a.getDiaSemana()).as("check diaSemana").isEqualTo(expected.getDiaSemana()))
            .satisfies(a -> assertThat(a.getHoraInicio()).as("check horaInicio").isEqualTo(expected.getHoraInicio()))
            .satisfies(a -> assertThat(a.getHoraFin()).as("check horaFin").isEqualTo(expected.getHoraFin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHorarioAtencionUpdatableRelationshipsEquals(HorarioAtencion expected, HorarioAtencion actual) {
        assertThat(actual)
            .as("Verify HorarioAtencion relationships")
            .satisfies(a -> assertThat(a.getMedico()).as("check medico").isEqualTo(expected.getMedico()));
    }
}
